[tool.black]
line-length = 140
target-version = ['py310']
include = '\.pyi?$'

[tool.pylint.master]
#ignore="tests,test_integrations"
ignore-patterns=["test_.*"]
load-plugins=["pylint.extensions.no_self_use"]

[tool.pylint.messages_control]
max-line-length = 140
disable = ["import-error",
    "missing-module-docstring",
    "missing-class-docstring",
    "invalid-name",
    "no-name-in-module",
    "missing-function-docstring",
    "too-few-public-methods",
    "too-many-instance-attributes",
    "logging-fstring-interpolation"]
output-format = "colorized"
max-locals=30
max-args=10
enable="useless-suppression"
